// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APIResponseCard struct {
	Status  string        `json:"status"`
	Message string        `json:"message"`
	Data    *CardResponse `json:"data,omitempty"`
}

type APIResponseCardAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseCardDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseCardDeleteAt struct {
	Status  string                `json:"status"`
	Message string                `json:"message"`
	Data    *CardResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseDashboardCard struct {
	Status  string                 `json:"status"`
	Message string                 `json:"message"`
	Data    *CardDashboardResponse `json:"data,omitempty"`
}

type APIResponseDashboardCardNumber struct {
	Status  string                         `json:"status"`
	Message string                         `json:"message"`
	Data    *CardDashboardByNumberResponse `json:"data,omitempty"`
}

type APIResponseGetMe struct {
	Status  string        `json:"status"`
	Message string        `json:"message"`
	Data    *UserResponse `json:"data,omitempty"`
}

type APIResponseLogin struct {
	Status  string         `json:"status"`
	Message string         `json:"message"`
	Data    *TokenResponse `json:"data,omitempty"`
}

type APIResponseMerchant struct {
	Status  string            `json:"status"`
	Message string            `json:"message"`
	Data    *MerchantResponse `json:"data,omitempty"`
}

type APIResponseMerchantAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseMerchantDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseMerchantDeleteAt struct {
	Status  string                    `json:"status"`
	Message string                    `json:"message"`
	Data    *MerchantResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseMerchantDeleteAtPagination struct {
	Status     string                      `json:"status"`
	Message    string                      `json:"message"`
	Data       []*MerchantResponseDeleteAt `json:"data"`
	Pagination *PaginationMeta             `json:"pagination,omitempty"`
}

type APIResponseMerchantMonthlyAmount struct {
	Status  string                           `json:"status"`
	Message string                           `json:"message"`
	Data    []*MerchantMonthlyAmountResponse `json:"data"`
}

type APIResponseMerchantMonthlyPaymentMethod struct {
	Status  string                                  `json:"status"`
	Message string                                  `json:"message"`
	Data    []*MerchantMonthlyPaymentMethodResponse `json:"data"`
}

type APIResponseMerchantMonthlyTotalAmount struct {
	Status  string                                `json:"status"`
	Message string                                `json:"message"`
	Data    []*MerchantMonthlyTotalAmountResponse `json:"data"`
}

type APIResponseMerchantPagination struct {
	Status     string              `json:"status"`
	Message    string              `json:"message"`
	Data       []*MerchantResponse `json:"data"`
	Pagination *PaginationMeta     `json:"pagination,omitempty"`
}

type APIResponseMerchantTransactionPagination struct {
	Status     string                         `json:"status"`
	Message    string                         `json:"message"`
	Data       []*MerchantTransactionResponse `json:"data"`
	Pagination *PaginationMeta                `json:"pagination,omitempty"`
}

type APIResponseMerchantYearlyAmount struct {
	Status  string                          `json:"status"`
	Message string                          `json:"message"`
	Data    []*MerchantYearlyAmountResponse `json:"data"`
}

type APIResponseMerchantYearlyPaymentMethod struct {
	Status  string                                 `json:"status"`
	Message string                                 `json:"message"`
	Data    []*MerchantYearlyPaymentMethodResponse `json:"data"`
}

type APIResponseMerchantYearlyTotalAmount struct {
	Status  string                               `json:"status"`
	Message string                               `json:"message"`
	Data    []*MerchantYearlyTotalAmountResponse `json:"data"`
}

type APIResponseMonthSaldoBalances struct {
	Status  string                       `json:"status"`
	Message string                       `json:"message"`
	Data    []*SaldoMonthBalanceResponse `json:"data,omitempty"`
}

type APIResponseMonthTotalSaldo struct {
	Status  string                            `json:"status"`
	Message string                            `json:"message"`
	Data    []*SaldoMonthTotalBalanceResponse `json:"data,omitempty"`
}

type APIResponseMonthlyAmount struct {
	Status  string                       `json:"status"`
	Message string                       `json:"message"`
	Data    []*CardMonthlyAmountResponse `json:"data"`
}

type APIResponseMonthlyBalance struct {
	Status  string                        `json:"status"`
	Message string                        `json:"message"`
	Data    []*CardMonthlyBalanceResponse `json:"data"`
}

type APIResponsePaginationCard struct {
	Status     string          `json:"status"`
	Message    string          `json:"message"`
	Data       []*CardResponse `json:"data"`
	Pagination *PaginationMeta `json:"pagination"`
}

type APIResponsePaginationCardDeleteAt struct {
	Status     string                  `json:"status"`
	Message    string                  `json:"message"`
	Data       []*CardResponseDeleteAt `json:"data"`
	Pagination *PaginationMeta         `json:"pagination"`
}

type APIResponsePaginationRole struct {
	Status     string          `json:"status"`
	Message    string          `json:"message"`
	Data       []*RoleResponse `json:"data,omitempty"`
	Pagination *PaginationMeta `json:"pagination,omitempty"`
}

type APIResponsePaginationRoleDeleteAt struct {
	Status     string                  `json:"status"`
	Message    string                  `json:"message"`
	Data       []*RoleResponseDeleteAt `json:"data,omitempty"`
	Pagination *PaginationMeta         `json:"pagination,omitempty"`
}

type APIResponsePaginationSaldo struct {
	Status     string           `json:"status"`
	Message    string           `json:"message"`
	Data       []*SaldoResponse `json:"data,omitempty"`
	Pagination *PaginationMeta  `json:"pagination,omitempty"`
}

type APIResponsePaginationSaldoDeleteAt struct {
	Status     string                   `json:"status"`
	Message    string                   `json:"message"`
	Data       []*SaldoResponseDeleteAt `json:"data,omitempty"`
	Pagination *PaginationMeta          `json:"pagination,omitempty"`
}

type APIResponsePaginationTopup struct {
	Status     string           `json:"status"`
	Message    string           `json:"message"`
	Data       []*TopupResponse `json:"data,omitempty"`
	Pagination *PaginationMeta  `json:"pagination,omitempty"`
}

type APIResponsePaginationTopupDeleteAt struct {
	Status     string                   `json:"status"`
	Message    string                   `json:"message"`
	Data       []*TopupResponseDeleteAt `json:"data,omitempty"`
	Pagination *PaginationMeta          `json:"pagination,omitempty"`
}

type APIResponsePaginationTransaction struct {
	Status     string                 `json:"status"`
	Message    string                 `json:"message"`
	Data       []*TransactionResponse `json:"data"`
	Pagination *PaginationMeta        `json:"pagination,omitempty"`
}

type APIResponsePaginationTransactionDeleteAt struct {
	Status     string                         `json:"status"`
	Message    string                         `json:"message"`
	Data       []*TransactionResponseDeleteAt `json:"data"`
	Pagination *PaginationMeta                `json:"pagination,omitempty"`
}

type APIResponsePaginationTransfer struct {
	Status     string              `json:"status"`
	Message    string              `json:"message"`
	Data       []*TransferResponse `json:"data"`
	Pagination *PaginationMeta     `json:"pagination,omitempty"`
}

type APIResponsePaginationTransferDeleteAt struct {
	Status     string                      `json:"status"`
	Message    string                      `json:"message"`
	Data       []*TransferResponseDeleteAt `json:"data"`
	Pagination *PaginationMeta             `json:"pagination,omitempty"`
}

type APIResponsePaginationUser struct {
	Status     string          `json:"status"`
	Message    string          `json:"message"`
	Data       []*UserResponse `json:"data"`
	Pagination *PaginationMeta `json:"pagination"`
}

type APIResponsePaginationUserDeleteAt struct {
	Status     string                  `json:"status"`
	Message    string                  `json:"message"`
	Data       []*UserResponseDeleteAt `json:"data"`
	Pagination *PaginationMeta         `json:"pagination"`
}

type APIResponsePaginationWithdraw struct {
	Status     string              `json:"status"`
	Message    string              `json:"message"`
	Data       []*WithdrawResponse `json:"data"`
	Pagination *PaginationMeta     `json:"pagination,omitempty"`
}

type APIResponsePaginationWithdrawDeleteAt struct {
	Status     string                      `json:"status"`
	Message    string                      `json:"message"`
	Data       []*WithdrawResponseDeleteAt `json:"data"`
	Pagination *PaginationMeta             `json:"pagination,omitempty"`
}

type APIResponseRefreshToken struct {
	Status  string         `json:"status"`
	Message string         `json:"message"`
	Data    *TokenResponse `json:"data,omitempty"`
}

type APIResponseRegister struct {
	Status  string        `json:"status"`
	Message string        `json:"message"`
	Data    *UserResponse `json:"data,omitempty"`
}

type APIResponseRole struct {
	Status  string        `json:"status"`
	Message string        `json:"message"`
	Data    *RoleResponse `json:"data,omitempty"`
}

type APIResponseRoleAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseRoleDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseRoleDeleteAt struct {
	Status  string                `json:"status"`
	Message string                `json:"message"`
	Data    *RoleResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseSaldoAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseSaldoDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseSaldoResponse struct {
	Status  string         `json:"status"`
	Message string         `json:"message"`
	Data    *SaldoResponse `json:"data,omitempty"`
}

type APIResponseSaldoResponseDeleteAt struct {
	Status  string                 `json:"status"`
	Message string                 `json:"message"`
	Data    *SaldoResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseTopup struct {
	Status  string         `json:"status"`
	Message string         `json:"message"`
	Data    *TopupResponse `json:"data,omitempty"`
}

type APIResponseTopupAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseTopupDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseTopupDeleteAt struct {
	Status  string                 `json:"status"`
	Message string                 `json:"message"`
	Data    *TopupResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseTopupMonthAmount struct {
	Status  string                      `json:"status"`
	Message string                      `json:"message"`
	Data    []*TopupMonthAmountResponse `json:"data,omitempty"`
}

type APIResponseTopupMonthMethod struct {
	Status  string                      `json:"status"`
	Message string                      `json:"message"`
	Data    []*TopupMonthMethodResponse `json:"data,omitempty"`
}

type APIResponseTopupMonthStatusFailed struct {
	Status  string                            `json:"status"`
	Message string                            `json:"message"`
	Data    []*TopupMonthStatusFailedResponse `json:"data,omitempty"`
}

type APIResponseTopupMonthStatusSuccess struct {
	Status  string                             `json:"status"`
	Message string                             `json:"message"`
	Data    []*TopupMonthStatusSuccessResponse `json:"data,omitempty"`
}

type APIResponseTopupYearAmount struct {
	Status  string                     `json:"status"`
	Message string                     `json:"message"`
	Data    []*TopupYearAmountResponse `json:"data,omitempty"`
}

type APIResponseTopupYearMethod struct {
	Status  string                     `json:"status"`
	Message string                     `json:"message"`
	Data    []*TopupYearMethodResponse `json:"data,omitempty"`
}

type APIResponseTopupYearStatusFailed struct {
	Status  string                           `json:"status"`
	Message string                           `json:"message"`
	Data    []*TopupYearStatusFailedResponse `json:"data,omitempty"`
}

type APIResponseTopupYearStatusSuccess struct {
	Status  string                            `json:"status"`
	Message string                            `json:"message"`
	Data    []*TopupYearStatusSuccessResponse `json:"data,omitempty"`
}

type APIResponseTransaction struct {
	Status  string               `json:"status"`
	Message string               `json:"message"`
	Data    *TransactionResponse `json:"data,omitempty"`
}

type APIResponseTransactionAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseTransactionDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseTransactionDeleteAt struct {
	Status  string                       `json:"status"`
	Message string                       `json:"message"`
	Data    *TransactionResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseTransactionMonthAmount struct {
	Status  string                            `json:"status"`
	Message string                            `json:"message"`
	Data    []*TransactionMonthAmountResponse `json:"data"`
}

type APIResponseTransactionMonthMethod struct {
	Status  string                            `json:"status"`
	Message string                            `json:"message"`
	Data    []*TransactionMonthMethodResponse `json:"data"`
}

type APIResponseTransactionMonthStatusFailed struct {
	Status  string                                  `json:"status"`
	Message string                                  `json:"message"`
	Data    []*TransactionMonthStatusFailedResponse `json:"data"`
}

type APIResponseTransactionMonthStatusSuccess struct {
	Status  string                                   `json:"status"`
	Message string                                   `json:"message"`
	Data    []*TransactionMonthStatusSuccessResponse `json:"data"`
}

type APIResponseTransactionYearAmount struct {
	Status  string                             `json:"status"`
	Message string                             `json:"message"`
	Data    []*TransactionYearlyAmountResponse `json:"data"`
}

type APIResponseTransactionYearMethod struct {
	Status  string                           `json:"status"`
	Message string                           `json:"message"`
	Data    []*TransactionYearMethodResponse `json:"data"`
}

type APIResponseTransactionYearStatusFailed struct {
	Status  string                                 `json:"status"`
	Message string                                 `json:"message"`
	Data    []*TransactionYearStatusFailedResponse `json:"data"`
}

type APIResponseTransactionYearStatusSuccess struct {
	Status  string                                  `json:"status"`
	Message string                                  `json:"message"`
	Data    []*TransactionYearStatusSuccessResponse `json:"data"`
}

type APIResponseTransactions struct {
	Status  string                 `json:"status"`
	Message string                 `json:"message"`
	Data    []*TransactionResponse `json:"data"`
}

type APIResponseTransfer struct {
	Status  string            `json:"status"`
	Message string            `json:"message"`
	Data    *TransferResponse `json:"data,omitempty"`
}

type APIResponseTransferAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseTransferDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseTransferDeleteAt struct {
	Status  string                    `json:"status"`
	Message string                    `json:"message"`
	Data    *TransferResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseTransferMonthAmount struct {
	Status  string                         `json:"status"`
	Message string                         `json:"message"`
	Data    []*TransferMonthAmountResponse `json:"data"`
}

type APIResponseTransferMonthStatusFailed struct {
	Status  string                               `json:"status"`
	Message string                               `json:"message"`
	Data    []*TransferMonthStatusFailedResponse `json:"data"`
}

type APIResponseTransferMonthStatusSuccess struct {
	Status  string                                `json:"status"`
	Message string                                `json:"message"`
	Data    []*TransferMonthStatusSuccessResponse `json:"data"`
}

type APIResponseTransferYearAmount struct {
	Status  string                        `json:"status"`
	Message string                        `json:"message"`
	Data    []*TransferYearAmountResponse `json:"data"`
}

type APIResponseTransferYearStatusFailed struct {
	Status  string                              `json:"status"`
	Message string                              `json:"message"`
	Data    []*TransferYearStatusFailedResponse `json:"data"`
}

type APIResponseTransferYearStatusSuccess struct {
	Status  string                               `json:"status"`
	Message string                               `json:"message"`
	Data    []*TransferYearStatusSuccessResponse `json:"data"`
}

type APIResponseTransfers struct {
	Status  string              `json:"status"`
	Message string              `json:"message"`
	Data    []*TransferResponse `json:"data"`
}

type APIResponseUserAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseUserDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseUserResponse struct {
	Status  string        `json:"status"`
	Message string        `json:"message"`
	Data    *UserResponse `json:"data,omitempty"`
}

type APIResponseUserResponseDeleteAt struct {
	Status  string                `json:"status"`
	Message string                `json:"message"`
	Data    *UserResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseWithdraw struct {
	Status  string            `json:"status"`
	Message string            `json:"message"`
	Data    *WithdrawResponse `json:"data,omitempty"`
}

type APIResponseWithdrawAll struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseWithdrawDelete struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type APIResponseWithdrawDeleteAt struct {
	Status  string                    `json:"status"`
	Message string                    `json:"message"`
	Data    *WithdrawResponseDeleteAt `json:"data,omitempty"`
}

type APIResponseWithdrawMonthAmount struct {
	Status  string                           `json:"status"`
	Message string                           `json:"message"`
	Data    []*WithdrawMonthlyAmountResponse `json:"data"`
}

type APIResponseWithdrawMonthStatusFailed struct {
	Status  string                               `json:"status"`
	Message string                               `json:"message"`
	Data    []*WithdrawMonthStatusFailedResponse `json:"data"`
}

type APIResponseWithdrawMonthStatusSuccess struct {
	Status  string                                `json:"status"`
	Message string                                `json:"message"`
	Data    []*WithdrawMonthStatusSuccessResponse `json:"data"`
}

type APIResponseWithdrawYearAmount struct {
	Status  string                          `json:"status"`
	Message string                          `json:"message"`
	Data    []*WithdrawYearlyAmountResponse `json:"data"`
}

type APIResponseWithdrawYearStatusFailed struct {
	Status  string                              `json:"status"`
	Message string                              `json:"message"`
	Data    []*WithdrawYearStatusFailedResponse `json:"data"`
}

type APIResponseWithdrawYearStatusSuccess struct {
	Status  string                               `json:"status"`
	Message string                               `json:"message"`
	Data    []*WithdrawYearStatusSuccessResponse `json:"data"`
}

type APIResponseYearSaldoBalances struct {
	Status  string                      `json:"status"`
	Message string                      `json:"message"`
	Data    []*SaldoYearBalanceResponse `json:"data,omitempty"`
}

type APIResponseYearTotalSaldo struct {
	Status  string                           `json:"status"`
	Message string                           `json:"message"`
	Data    []*SaldoYearTotalBalanceResponse `json:"data,omitempty"`
}

type APIResponseYearlyAmount struct {
	Status  string                      `json:"status"`
	Message string                      `json:"message"`
	Data    []*CardYearlyAmountResponse `json:"data"`
}

type APIResponseYearlyBalance struct {
	Status  string                       `json:"status"`
	Message string                       `json:"message"`
	Data    []*CardYearlyBalanceResponse `json:"data"`
}

type APIResponsesMerchant struct {
	Status  string              `json:"status"`
	Message string              `json:"message"`
	Data    []*MerchantResponse `json:"data"`
}

type APIResponsesRole struct {
	Status  string          `json:"status"`
	Message string          `json:"message"`
	Data    []*RoleResponse `json:"data,omitempty"`
}

type APIResponsesSaldo struct {
	Status  string           `json:"status"`
	Message string           `json:"message"`
	Data    []*SaldoResponse `json:"data,omitempty"`
}

type APIResponsesTopup struct {
	Status  string           `json:"status"`
	Message string           `json:"message"`
	Data    []*TopupResponse `json:"data,omitempty"`
}

type APIResponsesUser struct {
	Status  string          `json:"status"`
	Message string          `json:"message"`
	Data    []*UserResponse `json:"data"`
}

type APIResponsesWithdraw struct {
	Status  string              `json:"status"`
	Message string              `json:"message"`
	Data    []*WithdrawResponse `json:"data"`
}

type CardDashboardByNumberResponse struct {
	TotalBalance          int32 `json:"total_balance"`
	TotalTopup            int32 `json:"total_topup"`
	TotalWithdraw         int32 `json:"total_withdraw"`
	TotalTransaction      int32 `json:"total_transaction"`
	TotalTransferSend     int32 `json:"total_transfer_send"`
	TotalTransferReceiver int32 `json:"total_transfer_receiver"`
}

type CardDashboardResponse struct {
	TotalBalance     int32 `json:"total_balance"`
	TotalTopup       int32 `json:"total_topup"`
	TotalWithdraw    int32 `json:"total_withdraw"`
	TotalTransaction int32 `json:"total_transaction"`
	TotalTransfer    int32 `json:"total_transfer"`
}

type CardMonthlyAmountResponse struct {
	Month       string `json:"month"`
	TotalAmount int32  `json:"total_amount"`
}

type CardMonthlyBalanceResponse struct {
	Month        string `json:"month"`
	TotalBalance int32  `json:"total_balance"`
}

type CardResponse struct {
	ID           int32  `json:"id"`
	UserID       int32  `json:"user_id"`
	CardNumber   string `json:"card_number"`
	CardType     string `json:"card_type"`
	ExpireDate   string `json:"expire_date"`
	Cvv          string `json:"cvv"`
	CardProvider string `json:"card_provider"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type CardResponseDeleteAt struct {
	ID           int32   `json:"id"`
	UserID       int32   `json:"user_id"`
	CardNumber   string  `json:"card_number"`
	CardType     string  `json:"card_type"`
	ExpireDate   string  `json:"expire_date"`
	Cvv          string  `json:"cvv"`
	CardProvider string  `json:"card_provider"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at,omitempty"`
}

type CardYearlyAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"total_amount"`
}

type CardYearlyBalanceResponse struct {
	Year         string `json:"year"`
	TotalBalance int32  `json:"total_balance"`
}

type CreateCardInput struct {
	UserID       int32  `json:"user_id"`
	CardType     string `json:"card_type"`
	ExpireDate   string `json:"expire_date"`
	Cvv          string `json:"cvv"`
	CardProvider string `json:"card_provider"`
}

type CreateMerchantInput struct {
	Name   string `json:"name"`
	UserID int32  `json:"userId"`
}

type CreateRoleInput struct {
	Name string `json:"name"`
}

type CreateSaldoInput struct {
	CardNumber   string `json:"card_number"`
	TotalBalance int32  `json:"total_balance"`
}

type CreateTopupInput struct {
	CardNumber  string `json:"card_number"`
	TopupNo     string `json:"topup_no"`
	TopupAmount int32  `json:"topup_amount"`
	TopupMethod string `json:"topup_method"`
}

type CreateTransactionRequest struct {
	APIKey          string `json:"api_key"`
	CardNumber      string `json:"card_number"`
	Amount          int32  `json:"amount"`
	PaymentMethod   string `json:"payment_method"`
	MerchantID      int32  `json:"merchant_id"`
	TransactionTime string `json:"transaction_time"`
}

type CreateTransferRequest struct {
	TransferFrom   string `json:"transfer_from"`
	TransferTo     string `json:"transfer_to"`
	TransferAmount int32  `json:"transfer_amount"`
}

type CreateUserInput struct {
	Firstname       string `json:"firstname"`
	Lastname        string `json:"lastname"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type CreateWithdrawInput struct {
	CardNumber     string `json:"cardNumber"`
	WithdrawAmount int32  `json:"withdrawAmount"`
	WithdrawTime   string `json:"withdrawTime"`
}

type FindAllCardInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllMerchantApikeyInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"pageSize,omitempty"`
	Search   *string `json:"search,omitempty"`
	APIKey   *string `json:"apiKey,omitempty"`
}

type FindAllMerchantInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"pageSize,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllMerchantTransactionInput struct {
	Page       *int32  `json:"page,omitempty"`
	PageSize   *int32  `json:"pageSize,omitempty"`
	Search     *string `json:"search,omitempty"`
	MerchantID *int32  `json:"merchantId,omitempty"`
}

type FindAllRoleInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllSaldoInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllTopupByCardNumberInput struct {
	CardNumber string  `json:"card_number"`
	Page       *int32  `json:"page,omitempty"`
	PageSize   *int32  `json:"page_size,omitempty"`
	Search     *string `json:"search,omitempty"`
}

type FindAllTopupInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllTransactionCardNumberRequest struct {
	CardNumber string  `json:"card_number"`
	Page       *int32  `json:"page,omitempty"`
	PageSize   *int32  `json:"page_size,omitempty"`
	Search     *string `json:"search,omitempty"`
}

type FindAllTransactionRequest struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllTransferRequest struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllUserInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"page_size,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindAllWithdrawByCardNumberInput struct {
	CardNumber string  `json:"cardNumber"`
	Page       *int32  `json:"page,omitempty"`
	PageSize   *int32  `json:"pageSize,omitempty"`
	Search     *string `json:"search,omitempty"`
}

type FindAllWithdrawInput struct {
	Page     *int32  `json:"page,omitempty"`
	PageSize *int32  `json:"pageSize,omitempty"`
	Search   *string `json:"search,omitempty"`
}

type FindByAPIKeyInput struct {
	APIKey string `json:"apiKey"`
}

type FindByCardNumberInput struct {
	CardNumber string `json:"card_number"`
}

type FindByCardNumberTransferRequest struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
}

type FindByIDCardInput struct {
	CardID int32 `json:"card_id"`
}

type FindByIDMerchantInput struct {
	ID int32 `json:"id"`
}

type FindByIDRoleInput struct {
	RoleID int32 `json:"role_id"`
}

type FindByIDSaldoInput struct {
	ID int32 `json:"id"`
}

type FindByIDTopupInput struct {
	TopupID int32 `json:"topup_id"`
}

type FindByIDTransactionRequest struct {
	TransactionID int32 `json:"transaction_id"`
}

type FindByIDTransferRequest struct {
	TransferID int32 `json:"transfer_id"`
}

type FindByIDUserInput struct {
	ID int32 `json:"id"`
}

type FindByIDUserRoleInput struct {
	UserID int32 `json:"user_id"`
}

type FindByIDWithdrawInput struct {
	WithdrawID int32 `json:"withdrawId"`
}

type FindByMerchantUserIDInput struct {
	UserID int32 `json:"userId"`
}

type FindByUserIDCardInput struct {
	UserID int32 `json:"user_id"`
}

type FindByYearCardNumberTransactionRequest struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
}

type FindMonthlySaldoTotalBalanceInput struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type FindMonthlyTopupStatusCardNumberInput struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
	Month      int32  `json:"month"`
}

type FindMonthlyTopupStatusInput struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type FindMonthlyTransactionStatus struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type FindMonthlyTransactionStatusCardNumber struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
	Month      int32  `json:"month"`
}

type FindMonthlyTransferStatus struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type FindMonthlyTransferStatusCardNumber struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
	Month      int32  `json:"month"`
}

type FindMonthlyWithdrawStatusCardNumberInput struct {
	CardNumber string `json:"cardNumber"`
	Year       int32  `json:"year"`
	Month      int32  `json:"month"`
}

type FindMonthlyWithdrawStatusInput struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type FindTransactionByMerchantIDRequest struct {
	MerchantID int32 `json:"merchant_id"`
}

type FindTransferByTransferFromRequest struct {
	TransferFrom string `json:"transfer_from"`
}

type FindTransferByTransferToRequest struct {
	TransferTo string `json:"transfer_to"`
}

type FindYearAmountCardNumberInput struct {
	Year       int32  `json:"year"`
	CardNumber string `json:"card_number"`
}

type FindYearAmountInput struct {
	Year int32 `json:"year"`
}

type FindYearBalanceCardNumberInput struct {
	Year       int32  `json:"year"`
	CardNumber string `json:"card_number"`
}

type FindYearBalanceInput struct {
	Year int32 `json:"year"`
}

type FindYearMerchantByApikeyInput struct {
	Year   int32  `json:"year"`
	APIKey string `json:"apiKey"`
}

type FindYearMerchantByIDInput struct {
	Year       int32 `json:"year"`
	MerchantID int32 `json:"merchantId"`
}

type FindYearMerchantInput struct {
	Year int32 `json:"year"`
}

type FindYearTopupCardNumberInput struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
}

type FindYearTopupStatusCardNumberInput struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
}

type FindYearTopupStatusInput struct {
	Year int32 `json:"year"`
}

type FindYearTransactionStatus struct {
	Year int32 `json:"year"`
}

type FindYearTransactionStatusCardNumber struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
}

type FindYearTransferStatus struct {
	Year int32 `json:"year"`
}

type FindYearTransferStatusCardNumber struct {
	CardNumber string `json:"card_number"`
	Year       int32  `json:"year"`
}

type FindYearWithdrawCardNumberInput struct {
	CardNumber string `json:"cardNumber"`
	Year       int32  `json:"year"`
}

type FindYearWithdrawStatusCardNumberInput struct {
	CardNumber string `json:"cardNumber"`
	Year       int32  `json:"year"`
}

type FindYearWithdrawStatusInput struct {
	Year int32 `json:"year"`
}

type FindYearlySaldoInput struct {
	Year int32 `json:"year"`
}

type GetMeInput struct {
	AccessToken string `json:"access_token"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MerchantMonthlyAmountResponse struct {
	Month       string `json:"month"`
	TotalAmount int32  `json:"totalAmount"`
}

type MerchantMonthlyPaymentMethodResponse struct {
	Month         string `json:"month"`
	PaymentMethod string `json:"paymentMethod"`
	TotalAmount   int32  `json:"totalAmount"`
}

type MerchantMonthlyTotalAmountResponse struct {
	Month       string `json:"month"`
	Year        string `json:"year"`
	TotalAmount int32  `json:"totalAmount"`
}

type MerchantResponse struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	APIKey    string `json:"apiKey"`
	Status    string `json:"status"`
	UserID    int32  `json:"userId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type MerchantResponseDeleteAt struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	APIKey    string `json:"apiKey"`
	Status    string `json:"status"`
	UserID    int32  `json:"userId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	DeletedAt string `json:"deletedAt"`
}

type MerchantTransactionResponse struct {
	ID              int32   `json:"id"`
	CardNumber      string  `json:"cardNumber"`
	Amount          int32   `json:"amount"`
	PaymentMethod   string  `json:"paymentMethod"`
	MerchantID      int32   `json:"merchantId"`
	MerchantName    string  `json:"merchantName"`
	TransactionTime string  `json:"transactionTime"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
	DeletedAt       *string `json:"deletedAt,omitempty"`
}

type MerchantYearlyAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"totalAmount"`
}

type MerchantYearlyPaymentMethodResponse struct {
	Year          string `json:"year"`
	PaymentMethod string `json:"paymentMethod"`
	TotalAmount   int32  `json:"totalAmount"`
}

type MerchantYearlyTotalAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"totalAmount"`
}

type Mutation struct {
}

type PaginationMeta struct {
	CurrentPage  int32 `json:"current_page"`
	PageSize     int32 `json:"page_size"`
	TotalPages   int32 `json:"total_pages"`
	TotalRecords int32 `json:"total_records"`
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refresh_token"`
}

type RegisterInput struct {
	Firstname       string `json:"firstname"`
	Lastname        string `json:"lastname"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type RoleResponse struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RoleResponseDeleteAt struct {
	ID        int32   `json:"id"`
	Name      string  `json:"name"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type SaldoMonthBalanceResponse struct {
	Month        string `json:"month"`
	TotalBalance int32  `json:"total_balance"`
}

type SaldoMonthTotalBalanceResponse struct {
	Month        string `json:"month"`
	Year         string `json:"year"`
	TotalBalance int32  `json:"total_balance"`
}

type SaldoResponse struct {
	ID             int32   `json:"id"`
	CardNumber     string  `json:"card_number"`
	TotalBalance   int32   `json:"total_balance"`
	WithdrawTime   *string `json:"withdraw_time,omitempty"`
	WithdrawAmount *int32  `json:"withdraw_amount,omitempty"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

type SaldoResponseDeleteAt struct {
	ID             int32   `json:"id"`
	CardNumber     string  `json:"card_number"`
	TotalBalance   int32   `json:"total_balance"`
	WithdrawTime   *string `json:"withdraw_time,omitempty"`
	WithdrawAmount *int32  `json:"withdraw_amount,omitempty"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	DeletedAt      *string `json:"deleted_at,omitempty"`
}

type SaldoYearBalanceResponse struct {
	Year         string `json:"year"`
	TotalBalance int32  `json:"total_balance"`
}

type SaldoYearTotalBalanceResponse struct {
	Year         string `json:"year"`
	TotalBalance int32  `json:"total_balance"`
}

type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type TopupMonthAmountResponse struct {
	Month       string `json:"month"`
	TotalAmount int32  `json:"total_amount"`
}

type TopupMonthMethodResponse struct {
	Month       string `json:"month"`
	TopupMethod string `json:"topup_method"`
	TotalTopups int32  `json:"total_topups"`
	TotalAmount int32  `json:"total_amount"`
}

type TopupMonthStatusFailedResponse struct {
	Year        string `json:"year"`
	Month       string `json:"month"`
	TotalFailed int32  `json:"total_failed"`
	TotalAmount int32  `json:"total_amount"`
}

type TopupMonthStatusSuccessResponse struct {
	Year         string `json:"year"`
	Month        string `json:"month"`
	TotalSuccess int32  `json:"total_success"`
	TotalAmount  int32  `json:"total_amount"`
}

type TopupResponse struct {
	ID          int32   `json:"id"`
	CardNumber  string  `json:"card_number"`
	TopupNo     string  `json:"topup_no"`
	TopupAmount int32   `json:"topup_amount"`
	TopupMethod string  `json:"topup_method"`
	TopupTime   *string `json:"topup_time,omitempty"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type TopupResponseDeleteAt struct {
	ID          int32   `json:"id"`
	CardNumber  string  `json:"card_number"`
	TopupNo     string  `json:"topup_no"`
	TopupAmount int32   `json:"topup_amount"`
	TopupMethod string  `json:"topup_method"`
	TopupTime   *string `json:"topup_time,omitempty"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *string `json:"deleted_at,omitempty"`
}

type TopupYearAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"total_amount"`
}

type TopupYearMethodResponse struct {
	Year        string `json:"year"`
	TopupMethod string `json:"topup_method"`
	TotalTopups int32  `json:"total_topups"`
	TotalAmount int32  `json:"total_amount"`
}

type TopupYearStatusFailedResponse struct {
	Year        string `json:"year"`
	TotalFailed int32  `json:"total_failed"`
	TotalAmount int32  `json:"total_amount"`
}

type TopupYearStatusSuccessResponse struct {
	Year         string `json:"year"`
	TotalSuccess int32  `json:"total_success"`
	TotalAmount  int32  `json:"total_amount"`
}

type TransactionMonthAmountResponse struct {
	Month       string `json:"month"`
	TotalAmount int32  `json:"total_amount"`
}

type TransactionMonthMethodResponse struct {
	Month             string `json:"month"`
	PaymentMethod     string `json:"payment_method"`
	TotalTransactions int32  `json:"total_transactions"`
	TotalAmount       int32  `json:"total_amount"`
}

type TransactionMonthStatusFailedResponse struct {
	Year        string `json:"year"`
	Month       string `json:"month"`
	TotalFailed int32  `json:"total_failed"`
	TotalAmount int32  `json:"total_amount"`
}

type TransactionMonthStatusSuccessResponse struct {
	Year         string `json:"year"`
	Month        string `json:"month"`
	TotalSuccess int32  `json:"total_success"`
	TotalAmount  int32  `json:"total_amount"`
}

type TransactionResponse struct {
	ID              int32  `json:"id"`
	CardNumber      string `json:"card_number"`
	TransactionNo   string `json:"transaction_no"`
	Amount          int32  `json:"amount"`
	PaymentMethod   string `json:"payment_method"`
	MerchantID      int32  `json:"merchant_id"`
	TransactionTime string `json:"transaction_time"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type TransactionResponseDeleteAt struct {
	ID              int32   `json:"id"`
	CardNumber      string  `json:"card_number"`
	TransactionNo   string  `json:"transaction_no"`
	Amount          int32   `json:"amount"`
	PaymentMethod   string  `json:"payment_method"`
	MerchantID      int32   `json:"merchant_id"`
	TransactionTime string  `json:"transaction_time"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	DeletedAt       *string `json:"deleted_at,omitempty"`
}

type TransactionYearMethodResponse struct {
	Year              string `json:"year"`
	PaymentMethod     string `json:"payment_method"`
	TotalTransactions int32  `json:"total_transactions"`
	TotalAmount       int32  `json:"total_amount"`
}

type TransactionYearStatusFailedResponse struct {
	Year        string `json:"year"`
	TotalFailed int32  `json:"total_failed"`
	TotalAmount int32  `json:"total_amount"`
}

type TransactionYearStatusSuccessResponse struct {
	Year         string `json:"year"`
	TotalSuccess int32  `json:"total_success"`
	TotalAmount  int32  `json:"total_amount"`
}

type TransactionYearlyAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"total_amount"`
}

type TransferMonthAmountResponse struct {
	Month       string `json:"month"`
	TotalAmount int32  `json:"total_amount"`
}

type TransferMonthStatusFailedResponse struct {
	Year        string `json:"year"`
	Month       string `json:"month"`
	TotalFailed int32  `json:"total_failed"`
	TotalAmount int32  `json:"total_amount"`
}

type TransferMonthStatusSuccessResponse struct {
	Year         string `json:"year"`
	Month        string `json:"month"`
	TotalSuccess int32  `json:"total_success"`
	TotalAmount  int32  `json:"total_amount"`
}

type TransferResponse struct {
	ID             int32  `json:"id"`
	TransferNo     string `json:"transfer_no"`
	TransferFrom   string `json:"transfer_from"`
	TransferTo     string `json:"transfer_to"`
	TransferAmount int32  `json:"transfer_amount"`
	TransferTime   string `json:"transfer_time"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type TransferResponseDeleteAt struct {
	ID             int32   `json:"id"`
	TransferNo     string  `json:"transfer_no"`
	TransferFrom   string  `json:"transfer_from"`
	TransferTo     string  `json:"transfer_to"`
	TransferAmount int32   `json:"transfer_amount"`
	TransferTime   string  `json:"transfer_time"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	DeletedAt      *string `json:"deleted_at,omitempty"`
}

type TransferYearAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"total_amount"`
}

type TransferYearStatusFailedResponse struct {
	Year        string `json:"year"`
	TotalFailed int32  `json:"total_failed"`
	TotalAmount int32  `json:"total_amount"`
}

type TransferYearStatusSuccessResponse struct {
	Year         string `json:"year"`
	TotalSuccess int32  `json:"total_success"`
	TotalAmount  int32  `json:"total_amount"`
}

type UpdateCardInput struct {
	ID           int32  `json:"id"`
	UserID       int32  `json:"user_id"`
	CardType     string `json:"card_type"`
	ExpireDate   string `json:"expire_date"`
	Cvv          string `json:"cvv"`
	CardProvider string `json:"card_provider"`
}

type UpdateMerchantInput struct {
	MerchantID int32   `json:"merchantId"`
	Name       *string `json:"name,omitempty"`
	UserID     *int32  `json:"userId,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type UpdateRoleInput struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type UpdateSaldoInput struct {
	ID           int32   `json:"id"`
	CardNumber   *string `json:"card_number,omitempty"`
	TotalBalance *int32  `json:"total_balance,omitempty"`
}

type UpdateTopupInput struct {
	TopupID     int32   `json:"topup_id"`
	CardNumber  *string `json:"card_number,omitempty"`
	TopupAmount *int32  `json:"topup_amount,omitempty"`
	TopupMethod *string `json:"topup_method,omitempty"`
}

type UpdateTransactionRequest struct {
	ID              int32  `json:"id"`
	APIKey          string `json:"api_key"`
	CardNumber      string `json:"card_number"`
	Amount          int32  `json:"amount"`
	PaymentMethod   string `json:"payment_method"`
	MerchantID      int32  `json:"merchant_id"`
	TransactionTime string `json:"transaction_time"`
}

type UpdateTransferRequest struct {
	TransferID     int32  `json:"transfer_id"`
	TransferFrom   string `json:"transfer_from"`
	TransferTo     string `json:"transfer_to"`
	TransferAmount int32  `json:"transfer_amount"`
}

type UpdateUserInput struct {
	ID              int32   `json:"id"`
	Firstname       *string `json:"firstname,omitempty"`
	Lastname        *string `json:"lastname,omitempty"`
	Email           *string `json:"email,omitempty"`
	Password        *string `json:"password,omitempty"`
	ConfirmPassword *string `json:"confirm_password,omitempty"`
}

type UpdateWithdrawInput struct {
	WithdrawID     int32  `json:"withdrawId"`
	CardNumber     string `json:"cardNumber"`
	WithdrawAmount int32  `json:"withdrawAmount"`
	WithdrawTime   string `json:"withdrawTime"`
}

type UserResponse struct {
	ID        int32  `json:"id"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserResponseDeleteAt struct {
	ID        int32   `json:"id"`
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Email     string  `json:"email"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type WithdrawMonthStatusFailedResponse struct {
	Year        string `json:"year"`
	Month       string `json:"month"`
	TotalFailed int32  `json:"totalFailed"`
	TotalAmount int32  `json:"totalAmount"`
}

type WithdrawMonthStatusSuccessResponse struct {
	Year         string `json:"year"`
	Month        string `json:"month"`
	TotalSuccess int32  `json:"totalSuccess"`
	TotalAmount  int32  `json:"totalAmount"`
}

type WithdrawMonthlyAmountResponse struct {
	Month       string `json:"month"`
	TotalAmount int32  `json:"totalAmount"`
}

type WithdrawResponse struct {
	ID             int32  `json:"id"`
	WithdrawNo     string `json:"withdrawNo"`
	CardNumber     string `json:"cardNumber"`
	WithdrawAmount int32  `json:"withdrawAmount"`
	WithdrawTime   string `json:"withdrawTime"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
}

type WithdrawResponseDeleteAt struct {
	ID             int32   `json:"id"`
	WithdrawNo     string  `json:"withdrawNo"`
	CardNumber     string  `json:"cardNumber"`
	WithdrawAmount int32   `json:"withdrawAmount"`
	WithdrawTime   string  `json:"withdrawTime"`
	CreatedAt      string  `json:"createdAt"`
	UpdatedAt      string  `json:"updatedAt"`
	DeletedAt      *string `json:"deletedAt,omitempty"`
}

type WithdrawYearStatusFailedResponse struct {
	Year        string `json:"year"`
	TotalFailed int32  `json:"totalFailed"`
	TotalAmount int32  `json:"totalAmount"`
}

type WithdrawYearStatusSuccessResponse struct {
	Year         string `json:"year"`
	TotalSuccess int32  `json:"totalSuccess"`
	TotalAmount  int32  `json:"totalAmount"`
}

type WithdrawYearlyAmountResponse struct {
	Year        string `json:"year"`
	TotalAmount int32  `json:"totalAmount"`
}
